http_port 127.0.0.1:13128
visible_hostname asanpoc
http_access allow all
cache deny all
access_log stdio:/tmp/squid_repro/squid_run/access.log
cache_log /tmp/squid_repro/squid_run/cache.log
pid_filename /tmp/squid_repro/squid_run/squid.pid
coredump_dir /tmp/squid_repro/squid_run
mime_table /tmp/squid_repro/squid_run/mime.conf
unlinkd_program /tmp/squid_repro/squid_v5/src/unlinkd
icon_directory /tmp/squid_repro/squid_run/icons
error_directory /tmp/squid_repro/squid_v5/errors/templates
debug_options ALL,1 10,9
